SELECT
    c.MATERIAL,
    CASE WHEN km.BM IS NOT NULL
        THEN '<a href="http://drssai10.eu.infineon.com/Bedarfsmeldung/edit.asp?id=' || km.BM || '" target="_new">LINK</a>'
        ELSE NULL
    END AS BM_LINK,
    '<a href="\\Webspace.vih.infineon.com\webspace\Lagerbilder\Dresden\' || c.MATERIAL || '.jpg" target="_new">Bild</a>' AS BILD,
    max(s.MATERIALKURZTEXTDE)as MATERIALKURZTEXTDE,
    max(s.MATERIALKURZTEXTZ1)as MATERIALKURZTEXTZ1,
    max(s.FERTIGUNGSHINWEIS) as FERTIGUNGSHINWEIS,
    max(r.LIEFERANTNAME) as Regellieferant,
    MAX(r."Nettopreis in EUR")as Nettopreis_in_EUR,
    max(r.LIEFERANTENMATERIALNR)as LIEFERANTENMATERIALNR,
    max(s.DISPOMERKMAL)as DISPOMERKMAL,
    max(s.MELDEBESTAND)as Meldebestand,
    max(b.EIGENBESTAND_SUM_KONSIBESTAND)as EIGENBESTAND_SUM_KONSIBESTAND,
    max(b.GESAMTGESPERRT) as GESAMTGESPERRT,
    max(k.INITIALER_REQUESTOR)as Requestor,
    max(e.NAME) as Disponent,
    listagg(c.LIEFERANTENMATERIALNR, ', ') within group( order by c.LIEFERANTENMATERIALNR ) AS NOV_SEARCH
FROM (
    SELECT
        MATERIAL, LIEFERANTENMATERIALNR
    FROM
        MM_CHECK_PN
) c
LEFT JOIN (
    SELECT
        OBJEKT,
        ID_ELEKTRONISCHE_BEDARFSMELDG AS BM
    FROM
        MM_KLASSE_MAT_DRS
) km ON km.OBJEKT = c.MATERIAL
LEFT JOIN (
    SELECT
        MATERIAL,
        MATERIALKURZTEXTDE,
        MATERIALKURZTEXTZ1,
        DISPOMERKMAL,
        EINKÄUFERGRUPPE,
        MELDEBESTAND,
        FERTIGUNGSHINWEIS
    FROM
        MM_STAMMDATEN_DRS
)s on s.Material = c.MATERIAL
LEFT JOIN (
    SELECT
        MATERIAL,
        "Nettopreis in EUR",
        LIEFERANTENMATERIALNR,
        LIEFERANTNAME
    FROM
        MM_REGELLIEFERANT_DRS
) r on r.MATERIAL = c.MATERIAL
LEFT JOIN (
    SELECT
        MATERIAL,
        EIGENBESTAND_SUM_KONSIBESTAND,
        GESAMTGESPERRT
    FROM
        MM_BESTAND_DRS_VIEW
) b on b.MATERIAL = c.MATERIAL
LEFT JOIN (
    SELECT
        OBJEKT,
        INITIALER_REQUESTOR
    FROM
        MM_KLASSE_MAT_DRS
) k on k.OBJEKT = c.MATERIAL

LEFT JOIN (
    SELECT
        EINKAEUFERGRUPPE,
        NAME
    FROM
        MM_EINKAEUFER_DRS
) e on e.EINKAEUFERGRUPPE = s.EINKÄUFERGRUPPE

GROUP BY
    c.MATERIAL,
    km.BM
ORDER BY
    max(s.MATERIALKURZTEXTDE)
