select
am.LIEFERANTMATERIAL,
am.MATERIAL_SEARCH as ALLMATERIAL,
rp.MATERIAL_SEARCH as RMATERIAL
from HLP_PN_ZU_MATERAL_SEARCH am
    left join HLP_PN_ZU_RMATERAL_SEARCH rp on rp.LIEFERANTMATERIAL = am.LIEFERANTMATERIAL
