select
    h.MATERIAL,
    h.BATCH_NUMBER,
    h.GR_NUMBER,
    h.POSTING_DATE as DELIVERY_DATE,
    h.CONSUMPTION_DATE as CONSUMPTION_DATE,
    h.CONSUMPTION as QUANTITY
from MM_LAGERLIST_USAGE_HIST h
order by h.CONSUMPTION_DATE  DESC
